Update CLI Guide with new user flow
vmware/repository-service-tuf-cli pull request #231
Opened 2023-03-22 10:09 UTC by kairoaraujo

The CLI Guide is outdated after the new flow for adding the single online key.

This commit updates it.

Basically, it is a new copy from the CLI interface.
In some of `.. code::` the `shell` statement was removed due to incompatibility (special characters in the interface)

Closes #223

2023-03-23 18:08 UTC, MVrachev commented on docs/source/guide/index.rst
> +  3.  Run ``rstuf admin ceremony -b [-u filename]``
Isn't the `u` option required to upload it online?
As it seems that you document it as optional or am I wrong?

2023-03-27 12:13 UTC, kairoaraujo commented
> I left some suggestions.
> I want to remind you that if we do any changes in the documentation for the ceremony it will be good to also include them in the `ceremony.py` file as well.

What is inside `..code::` blocks are copied/pasted from `rstuf admin ceremony` (`ceremony.py`) CLI.
What you're suggesting is changing the `ceremony.py`, is it correct?

2023-03-27 13:20 UTC, kairoaraujo commented on docs/source/guide/index.rst
> +    See: TUF Specification about succinct hash bin delegation.
This is only a "screenshot". The CLI has a link.

2023-03-27 13:22 UTC, kairoaraujo commented on docs/source/guide/index.rst
> +    │ --save       -s        Save a copy of the metadata locally. This option saves the metadata files (json) in the 'metadata' folder │
Because there is no default (once save is a boolean option).

2023-03-27 14:43 UTC, MVrachev commented on docs/source/guide/index.rst
> +to load their keys.
I just noticed we mention `their` three times in a row now.
Maybe we can do something like:
```suggestion
The owners will need to be present to insert their keys and passwords
to load their keys.
```

2023-03-27 14:51 UTC, MVrachev commented on docs/source/guide/index.rst
> +    Reference: TUF expires
I am sorry, but I cannot find the `screenshots`.
I searched for them, but they are nowhere to be found.

2023-03-27 14:52 UTC, kairoaraujo commented on docs/source/guide/index.rst
> +    See: TUF Specification about succinct hash bin delegation.
Meaning that we mentioned it already in CLI. What you see in this documentation is only "screenshots" (ASCII copy/paste) from the rendered CLI interface.
https://github.com/vmware/repository-service-tuf-cli/blob/5eb03bf05ab5e345e81f8bef3c324993836164e2/repository_service_tuf/cli/admin/ceremony.py#L200-L203
![Screenshot 2023-03-27 at 16 52 10](https://user-images.githubusercontent.com/546882/227977342-b5109a6f-671d-4f6c-8588-f94a2c0bfb29.png)

2023-03-27 14:56 UTC, kairoaraujo commented on docs/source/guide/index.rst
> +    Reference: TUF Goals for PKI
We give the links.
This is just an example from the interface screen the user will see running the CLI. Take it as a "screenshot" for reference.
![Screenshot 2023-03-27 at 16 53 47](https://user-images.githubusercontent.com/546882/227978586-d6eb469b-4708-44fc-9dcc-934c2ffb9911.png)

2023-03-27 15:00 UTC, MVrachev commented on docs/source/guide/index.rst
> +    │ --save       -s        Save a copy of the metadata locally. This option saves the metadata files (json) in the 'metadata' folder │
Well, it seems there is a default value and the `show_default` option is `True` for `save`:
https://github.com/vmware/repository-service-tuf-cli/blob/5eb03bf05ab5e345e81f8bef3c324993836164e2/repository_service_tuf/cli/admin/ceremony.py#L719

2023-03-27 15:11 UTC, kairoaraujo commented on docs/source/guide/index.rst
> +    │ --save       -s        Save a copy of the metadata locally. This option saves the metadata files (json) in the 'metadata' folder │
It is an `is_flag`.
https://github.com/vmware/repository-service-tuf-cli/blob/5eb03bf05ab5e345e81f8bef3c324993836164e2/repository_service_tuf/cli/admin/ceremony.py#L721

An `is_flag` option is a boolean. It means if the user doesn't use `-save` it is False by default.
The user must give `-save` to save the JSON metadata.
It doesn't act like an option `-save true`, `-save false`
The option `-save` acts as a [switch ](https://click.palletsprojects.com/en/8.1.x/options/#feature-switches) if the user wants to save, they must use the flag.

2023-03-29 13:05 UTC, MVrachev requested changes

2023-03-29 13:05 UTC, MVrachev commented on docs/source/guide/index.rst
> +    Reference: TUF Goals for PKI
I see the box in which you document those stuff doesn't support rich text format or in other words text with an embedded link.

2023-03-29 13:34 UTC, MVrachev approved these changes

2023-03-29 19:33 UTC, merged